### ISSUE TITLE
Update Card Information

### ISSUE THREAD

**Issue by Simba98** [linziyou0601/yugioh-card-maker#4]
Could you update the newest card information or provide your script for generating the card information, like card picture and text?

**Comment by linziyou0601** [comment]
I was using the data in "YGOPro2" at the time, and the card pictures were converted one by one, so I'm afraid that I may not have time to update this part now.

**Comment by Simba98** [comment]
Thanks for your reply.
So, could you share the script or method for converting?

**Comment by linziyou0601** [comment]
The conversion script and the old db file are in `/static/ygo/cards.zip`, but I am not sure if the new db file format of YGOPro2 is applicable.

**Comment by Simba98** [comment]
Oh, sorry for missing that. I didn't try to unpack them.

Have a nice day, and keep safe.
